# Generated by Django 4.2.2 on 2023-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=150),
            preserve_default=False,
        ),
    ]
