# Generated by Django 4.2.2 on 2023-06-24 10:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
