# Generated by Django 4.2.2 on 2023-06-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_note_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_time']},
        ),
    ]
