# Generated by Django 4.2.2 on 2023-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
