# Generated by Django 4.2.2 on 2023-07-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_age_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
